<?php

namespace ContainerTKP7EhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\TestController' shared autowired service.
     *
     * @return \App\Controller\Admin\TestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/DashboardControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractDashboardController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/TestController.php';

        $container->services['App\\Controller\\Admin\\TestController'] = $instance = new \App\Controller\Admin\TestController();

        $instance->setContainer(($container->privates['.service_locator.XmW3LYn'] ?? $container->load('get_ServiceLocator_XmW3LYnService'))->withContext('App\\Controller\\Admin\\TestController', $container));

        return $instance;
    }
}
