<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTKP7EhH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTKP7EhH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTKP7EhH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTKP7EhH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTKP7EhH\App_KernelDevDebugContainer([
    'container.build_hash' => 'TKP7EhH',
    'container.build_id' => '6680c74b',
    'container.build_time' => 1658143724,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTKP7EhH');
