<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBCpezVW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBCpezVW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBCpezVW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBCpezVW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBCpezVW\App_KernelDevDebugContainer([
    'container.build_hash' => 'BCpezVW',
    'container.build_id' => 'e622764b',
    'container.build_time' => 1658178373,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBCpezVW');
